import { NextRequest, NextResponse } from "next/server";
import { withTenantDB } from "@/lib/core/tenant-db";
import { logger } from "@/lib/core/logger";
import { CredentialsService } from "@/lib/services/credentials.service";

const log = logger.withContext({ module: 'FollowUpCron' });

// ==========================================
// QUBA AI — Follow-Up Cron (Tenant-Aware)
// V2: Reads follow_up_enabled from channel_ai_profiles
// Rollback: USE_V2_FOLLOW_UP=false → settings table
//
// PHASE 2K: USE_V2_TASK_ENGINE=true → task-based executor
// Default: false (safe — V1 legacy runs)
// ==========================================

function isV2FollowUpEnabled(): boolean {
  return process.env.USE_V2_FOLLOW_UP !== 'false'; // default: true
}

function isTaskEngineEnabled(): boolean {
  return process.env.USE_V2_TASK_ENGINE === 'true'; // default: false (safe)
}

export async function GET(request: NextRequest) {
  // ── Route Auth Secret Guard ──
  const authHeader = request.headers.get('authorization');
  const cronSecret = process.env.CRON_SECRET;
  const urlSecret = request.nextUrl.searchParams.get('secret');

  const isCronAuth = (cronSecret && authHeader === `Bearer ${cronSecret}`) || (cronSecret && urlSecret === cronSecret);
  
  if (cronSecret && !isCronAuth) {
    log.warn('[FOLLOW_UP_AUTH_FAIL] Unauthorized request');
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  if (isTaskEngineEnabled()) {
    return handleV2TaskEngine(request);
  }
  return handleV1Legacy();
}

// ═══════════════════════════════════════════════════════════
// V2 TASK ENGINE — Phase 2K
// Feature flagged. USE_V2_TASK_ENGINE=true to activate.
// ═══════════════════════════════════════════════════════════

async function handleV2TaskEngine(request: NextRequest) {
  const startTime = Date.now();
  const dryRun = request.nextUrl.searchParams.get('dry_run') === 'true';
  const enableOrphanGen = process.env.ENABLE_V2_ORPHAN_TASK_GENERATION === 'true';

  try {
    const systemDb = withTenantDB('admin-system', true);
    
    const tenants = await systemDb.executeSafe({
      text: "SELECT id, slug FROM tenants WHERE status = 'active'"
    }) as any[];

    const results: any[] = [];
    let totalProcessed = 0;
    let totalSkipped = 0;
    let totalNotified = 0;
    let timeBudgetExceeded = false;
    const simulatedActions: any[] = [];

    for (const tenant of tenants) {
      // Enforce 7.5s (7500ms) Vercel Hobby time budget
      const elapsed = Date.now() - startTime;
      if (elapsed >= 7500) {
        timeBudgetExceeded = true;
        log.warn(`[V2_TASK_TIMEOUT] Time budget exceeded (elapsed ${elapsed}ms), pausing execution`);
        break;
      }

      try {
        const db = withTenantDB(tenant.id);
        const { TaskService } = await import('@/lib/services/task.service');
        const { NotificationService } = await import('@/lib/services/notification.service');
        const { StopRuleEngine } = await import('@/lib/services/stop-rules.service');
        
        const taskService = new TaskService(db);
        const notifService = new NotificationService(db);
        const stopRules = new StopRuleEngine(db);

        let processed = 0;
        let skipped = 0;
        let notified = 0;
        let autoGenerated = 0;

        // 1. Get pending tasks that are due now (tuned limit to 50 for Hobby safety)
        const dueTasks = await db.executeSafe({
          text: `SELECT t.*, o.stage as opp_stage, o.patient_name, o.country
                 FROM follow_up_tasks t
                 LEFT JOIN opportunities o ON o.id = t.opportunity_id AND o.tenant_id = t.tenant_id
                 WHERE t.tenant_id = $1 
                   AND t.status = 'pending' 
                   AND t.due_at <= NOW()
                 ORDER BY t.due_at ASC
                 LIMIT 50`,
          values: [tenant.id]
        }) as any[];

        for (const task of dueTasks) {
          // Check time budget inside loop
          if (Date.now() - startTime >= 7500) {
            timeBudgetExceeded = true;
            break;
          }

          // Evaluate stop rules
          const stopResult = await stopRules.evaluate({
            tenantId: tenant.id,
            opportunityId: task.opportunity_id,
            phoneNumber: task.phone_number,
            taskType: task.task_type,
            taskCreatedAt: task.created_at,
          });

          if (stopResult.shouldStop) {
            const stopReason = stopResult.reason || 'unknown';
            
            if (!dryRun) {
              // Semantic status mapping: skipped vs cancelled
              if (['lost', 'not_qualified', 'arrived', 'not_interested', 'appointment_booked', 'stage_terminal', 'patient_opted_out'].includes(stopReason)) {
                await taskService.cancel(task.id, tenant.id, `StopRule: ${stopReason}`);
              } else {
                await taskService.skip(task.id, tenant.id, `StopRule: ${stopReason}`);
              }
            }
            skipped++;
            totalSkipped++;
            simulatedActions.push({ 
              tenant: tenant.slug,
              taskId: task.id, 
              action: ['lost', 'not_qualified', 'arrived', 'not_interested', 'appointment_booked', 'stage_terminal', 'patient_opted_out'].includes(stopReason) ? 'cancelled' : 'skipped', 
              reason: stopReason 
            });
            continue;
          }

          // Deduplication spam block check
          const metadata = typeof task.metadata === 'string' ? JSON.parse(task.metadata) : (task.metadata || {});
          if (metadata.overdue_notified_at) {
            skipped++;
            totalSkipped++;
            simulatedActions.push({
              tenant: tenant.slug,
              taskId: task.id,
              action: 'skipped_deduplicated',
              reason: 'already_notified'
            });
            continue;
          }

          // If we proceed, generate panel / Telegram notifications
          if (!dryRun) {
            await notifService.send({
              tenantId: tenant.id,
              category: 'overdue_task',
              title: `⏰ Görev Zamanı Geldi: ${task.title}`,
              body: `${task.patient_name || task.phone_number} — ${task.task_type}`,
              priority: task.due_at && new Date(task.due_at).getTime() < Date.now() - 3600000 ? 'high' : 'normal',
              opportunityId: task.opportunity_id,
              taskId: task.id,
              conversationId: task.conversation_id,
              phoneNumber: task.phone_number,
            });

            // Mark task metadata with overdue_notified_at to prevent spam
            const updatedMetadata = { ...metadata, overdue_notified_at: new Date().toISOString() };
            await db.executeSafe({
              text: `UPDATE follow_up_tasks SET metadata = $1::jsonb, updated_at = NOW() WHERE id = $2 AND tenant_id = $3`,
              values: [JSON.stringify(updatedMetadata), task.id, tenant.id]
            });
          }

          notified++;
          totalNotified++;
          processed++;
          totalProcessed++;
          simulatedActions.push({ 
            tenant: tenant.slug,
            taskId: task.id, 
            action: 'notified', 
            title: task.title 
          });
        }

        // 2. Generate tasks for opportunities that need follow-up but have no pending task (Orphan Opportunities)
        if (enableOrphanGen && !timeBudgetExceeded) {
          const orphanOpps = await db.executeSafe({
            text: `SELECT o.id, o.phone_number, o.conversation_id, o.patient_name, o.department, o.country
                   FROM opportunities o
                   WHERE o.tenant_id = $1
                     AND o.stage NOT IN ('lost', 'not_qualified', 'arrived', 'booked')
                     AND o.next_follow_up_at IS NOT NULL
                     AND o.next_follow_up_at <= NOW()
                     AND NOT EXISTS (
                       SELECT 1 FROM follow_up_tasks t 
                       WHERE t.opportunity_id = o.id 
                         AND t.tenant_id = $1 
                         AND t.status IN ('pending', 'in_progress')
                     )
                   LIMIT 25`,
            values: [tenant.id]
          }) as any[];

          for (const opp of orphanOpps) {
            if (Date.now() - startTime >= 7500) {
              timeBudgetExceeded = true;
              break;
            }

            try {
              if (!dryRun) {
                await taskService.create({
                  tenantId: tenant.id,
                  opportunityId: opp.id,
                  conversationId: opp.conversation_id,
                  phoneNumber: opp.phone_number,
                  taskType: 'follow_up_no_response',
                  title: `📋 Takip — ${opp.patient_name || opp.phone_number}`,
                  description: `${opp.department || 'Genel'} — Cevapsız fırsat takibi`,
                  dueAt: new Date().toISOString(),
                  isAutomated: true,
                  createdBy: 'cron_v2',
                  sourceEvent: 'cron_follow_up',
                });
              }
              autoGenerated++;
              simulatedActions.push({ 
                tenant: tenant.slug,
                opportunityId: opp.id, 
                action: 'orphan_task_created', 
                title: `Takip — ${opp.patient_name || opp.phone_number}` 
              });
            } catch {
              // Skip individual errors
            }
          }
        }

        results.push({
          tenant: tenant.slug,
          mode: 'v2_task_engine',
          dueTasks: dueTasks.length,
          processed,
          skipped,
          notified,
          autoGenerated,
        });

      } catch (e: any) {
        results.push({ tenant: tenant.slug, error: e.message });
      }
    }

    const durationMs = Date.now() - startTime;

    return NextResponse.json({ 
      success: true, 
      engine: 'v2_task',
      dry_run: dryRun,
      processed_count: totalProcessed,
      skipped_count: totalSkipped,
      notified_count: totalNotified,
      time_budget_exceeded: timeBudgetExceeded,
      remaining_estimate: timeBudgetExceeded ? 1 : 0,
      duration_ms: durationMs,
      simulated_actions: simulatedActions,
      results 
    });
  } catch (e: any) {
    log.error("V2 Task Engine cron error", e instanceof Error ? e : new Error(String(e)));
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}

// ═══════════════════════════════════════════════════════════
// V1 LEGACY — Original follow-up cron behavior
// Untouched. USE_V2_TASK_ENGINE=false (default) runs this.
// ═══════════════════════════════════════════════════════════

async function handleV1Legacy() {
  try {
    const systemDb = withTenantDB('admin-system', true);
    
    // Tüm aktif tenantları al
    const tenants = await systemDb.executeSafe({
      text: "SELECT id, slug FROM tenants WHERE status = 'active'"
    }) as any[];
    
    const results: any[] = [];
    
    for (const tenant of tenants) {
      try {
        const db = withTenantDB(tenant.id);

        // ── Follow-up enabled kontrolü ──
        let isEnabled = true; // default: enabled

        if (isV2FollowUpEnabled()) {
          // V2: Read from channel_ai_profiles
          const followUpConfig = await db.executeSafe({
            text: `SELECT cap.follow_up_enabled 
                   FROM channel_ai_profiles cap
                   JOIN channel_groups cg ON cap.group_id = cg.id
                   WHERE cg.tenant_id = $1
                   ORDER BY cap.updated_at DESC LIMIT 1`,
            values: [tenant.id]
          }) as any[];

          if (followUpConfig.length > 0 && followUpConfig[0].follow_up_enabled === false) {
            isEnabled = false;
          }
          // No rows = default enabled
        } else {
          // V1 FALLBACK: Read from settings table
          const followUpSettings = await db.executeSafe({
            text: "SELECT value FROM settings WHERE key = 'bot_follow_up_enabled' AND tenant_id = $1",
            values: [tenant.id]
          }) as any[];

          if (followUpSettings.length > 0 && followUpSettings[0].value === 'false') {
            isEnabled = false;
          }
        }

        if (!isEnabled) {
          results.push({ tenant: tenant.slug, status: 'disabled' });
          continue;
        }

        // Takip gereken konuşmaları bul
        const conversations = await db.executeSafe({
          text: `
            SELECT c.phone_number, c.patient_name, c.follow_up_count, c.channel
            FROM conversations c
            WHERE c.tenant_id = $1
              AND c.status = 'bot'
              AND c.follow_up_count < 3
              AND c.last_message_at < NOW() - INTERVAL '24 hours'
              AND c.last_message_at > NOW() - INTERVAL '7 days'
              AND NOT EXISTS (
                SELECT 1 FROM messages m 
                WHERE m.phone_number = c.phone_number 
                  AND m.direction = 'in' 
                  AND m.created_at > c.last_message_at
                  AND m.tenant_id = $2
              )
            LIMIT 10
          `,
          values: [tenant.id, tenant.id]
        }) as any[];

        for (const conv of conversations) {
          try {
            // Follow-up mesajı gönder
            const count = (conv.follow_up_count || 0) + 1;
            const followUpMessages = [
              `Merhaba ${conv.patient_name || ''} 🙏 Daha önce iletişime geçmiştik. Tedavi süreciniz hakkında merak ettiğiniz bir şey var mı?`,
              `${conv.patient_name || 'Merhaba'}, sizinle ilgili merak ediyoruz. Sorularınız varsa yanıtlamaktan mutluluk duyarız 😊`,
              `Son hatırlatma: ${conv.patient_name || ''}, randevu planlamak isterseniz size yardımcı olmaktan memnuniyet duyarız. İyi günler dileriz 🌸`
            ];
            const msg = followUpMessages[Math.min(count - 1, 2)];

            // Mesaj gönder (WhatsApp kanalı için)
            if (conv.channel === 'whatsapp') {
              const creds = await CredentialsService.resolveCredentials(tenant.id, "whatsapp");
              const token = creds.accessToken;
              const phoneId = creds.whatsappPhoneNumberId;
              
              if (token && phoneId) {
                await fetch(`https://graph.facebook.com/v25.0/${phoneId}/messages`, {
                  method: "POST",
                  headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
                  body: JSON.stringify({
                    messaging_product: "whatsapp",
                    to: conv.phone_number,
                    type: "text",
                    text: { body: msg }
                  })
                });
              }
            }

            // DB güncelle
            await db.executeSafe({
              text: "UPDATE conversations SET follow_up_count = $1, last_message_at = NOW() WHERE phone_number = $2 AND tenant_id = $3",
              values: [count, conv.phone_number, tenant.id]
            });

            await db.executeSafe({
              text: "INSERT INTO messages (tenant_id, phone_number, direction, content, channel) VALUES ($1, $2, 'out', $3, $4)",
              values: [tenant.id, conv.phone_number, msg, conv.channel || 'whatsapp']
            });
            
          } catch (e: any) {
            log.error(`Follow-up hatası`, e instanceof Error ? e : new Error(String(e)), { phone: conv.phone_number });
          }
        }
        
        results.push({ tenant: tenant.slug, followUps: conversations.length });
      } catch (e: any) {
        results.push({ tenant: tenant.slug, error: e.message });
      }
    }

    return NextResponse.json({ success: true, results });
  } catch (e: any) {
    log.error("Follow-up cron hatası", e instanceof Error ? e : new Error(String(e)));
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
